# Generated by Django 4.1.7 on 2023-11-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Mobil_no', models.CharField(max_length=100, null=True)),
                ('Comments', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
