# Generated by Django 4.1.7 on 2024-01-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Class', models.CharField(max_length=100, null=True)),
                ('School', models.CharField(max_length=100, null=True)),
                ('DOB', models.CharField(max_length=100, null=True)),
                ('Age', models.CharField(max_length=100, null=True)),
                ('Father_name', models.CharField(max_length=100, null=True)),
                ('Mother_name', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Phone_no', models.CharField(max_length=100, null=True)),
                ('Father_phno', models.CharField(max_length=100, null=True)),
                ('Subject', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Add_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=100, null=True)),
                ('Name', models.CharField(max_length=255, null=True)),
                ('RollNo', models.CharField(max_length=1000, null=True)),
                ('All', models.CharField(max_length=100, null=True)),
                ('English', models.CharField(max_length=100, null=True)),
                ('Tamil', models.CharField(max_length=100, null=True)),
                ('Maths', models.CharField(max_length=100, null=True)),
                ('Science', models.CharField(max_length=100, null=True)),
                ('Social', models.CharField(max_length=100, null=True)),
                ('Physics', models.CharField(max_length=100, null=True)),
                ('Chemistry', models.CharField(max_length=100, null=True)),
                ('Biology', models.CharField(max_length=100, null=True)),
                ('Computer_Science', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Mobil_no', models.CharField(max_length=100, null=True)),
                ('Comments', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
