# Generated by Django 4.1.7 on 2023-11-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP_Classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Class', models.CharField(max_length=100, null=True)),
                ('School', models.CharField(max_length=100, null=True)),
                ('DOB', models.CharField(max_length=100, null=True)),
                ('Age', models.CharField(max_length=100, null=True)),
                ('Father_name', models.CharField(max_length=100, null=True)),
                ('Mother_name', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Phone_no', models.CharField(max_length=100, null=True)),
                ('Father_phno', models.CharField(max_length=100, null=True)),
                ('Subject', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
